apiVersion: v1
items:
- apiVersion: v1
  data:
    JWT_REFRESH_SECRET: Y2hhbmdlLXRoaXMtdG8tYW5vdGhlci1zZWN1cmUtMjU2LWJpdC1zZWNyZXQ=
    JWT_SECRET: Y2hhbmdlLXRoaXMtdG8tYS1zZWN1cmUtMjU2LWJpdC1zZWNyZXQta2V5
    MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlcGFzc3dvcmQxMjM=
    MONGO_INITDB_ROOT_USERNAME: bW9uZ28tYWRtaW4=
    MONGODB_URI: bW9uZ29kYjovL21vbmdvLWFkbWluOnNlY3VyZXBhc3N3b3JkMTIzQG1vbmdvZGItMC5tb25nb2RiLXNlcnZpY2UubWVybi1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvdXNlcm1hbmFnZW1lbnQ/YXV0aFNvdXJjZT1hZG1pbg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"app-secrets","namespace":"mern-app"},"stringData":{"JWT_REFRESH_SECRET":"change-this-to-another-secure-256-bit-secret","JWT_SECRET":"change-this-to-a-secure-256-bit-secret-key","MONGODB_URI":"mongodb://mongo-admin:securepassword123@mongodb-0.mongodb-service.mern-app.svc.cluster.local:27017/usermanagement?authSource=admin","MONGO_INITDB_ROOT_PASSWORD":"securepassword123","MONGO_INITDB_ROOT_USERNAME":"mongo-admin"},"type":"Opaque"}
    creationTimestamp: "2026-05-15T08:46:48Z"
    name: app-secrets
    namespace: mern-app
    resourceVersion: "1778834808225007003"
    uid: ac0d1978-134f-4500-befe-e35653305e0d
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
