apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mern-app
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo-admin:securepassword123@mongodb-0.mongodb-service.mern-app.svc.cluster.local:27017/usermanagement?authSource=admin"
  JWT_SECRET: "change-this-to-a-secure-256-bit-secret-key"
  JWT_REFRESH_SECRET: "change-this-to-another-secure-256-bit-secret"
  MONGO_INITDB_ROOT_USERNAME: "mongo-admin"
  MONGO_INITDB_ROOT_PASSWORD: "securepassword123"
